"""add github evidence tables

Revision ID: 416a133296a2
Revises: ffb149a1375c
Create Date: 2026-08-16 21:04:31.013224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416a133296a2'
down_revision: Union[str, Sequence[str], None] = 'ffb149a1375c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('repository_full_name', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_delivery_id'), 'webhook_events', ['delivery_id'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('owner_github_username', sa.String(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author_github_username', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('base_branch', sa.String(), nullable=True),
    sa.Column('head_branch', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author_github_username', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('files_changed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_table('commits')
    op.drop_table('pull_requests')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_webhook_events_delivery_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
