from app.schemas.project_architect import ArchitectMilestone, ArchitectPlan, ArchitectTask, ProjectDraftRequest

def local_plan(p: ProjectDraftRequest)->ArchitectPlan:
    stack=p.desired_stack[:6] or (['Python','FastAPI','PostgreSQL'] if 'api' in (p.title+' '+p.description).lower() else ['TypeScript','Next.js','PostgreSQL'])
    skills=stack[:3]
    milestones=[
      ArchitectMilestone(title='Define & Design',objective='Turn the idea into a small, testable product scope.',tasks=[
        ArchitectTask(title='Write the V1 problem and user flow',description='Define the primary user, problem, happy path, and explicit non-goals for this project.',completion_criteria='README contains the problem, target user, one happy-path flow, and at least three non-goals.',required_skills=['Product thinking','Technical writing'],resources=['Use official documentation for the selected stack; keep scope to one core flow.']),
        ArchitectTask(title='Design the data and API boundary',description='Sketch the minimum entities and interfaces needed for the core flow before implementation.',completion_criteria='Data entities and API/UI boundaries are documented and reviewable.',required_skills=['System design']+skills[:1],resources=['Prefer official framework/database documentation.'])]),
      ArchitectMilestone(title='Build the Core Flow',objective='Implement one end-to-end working path before adding breadth.',tasks=[
        ArchitectTask(title='Implement persistence and core backend behavior',description='Create the minimum storage and backend logic required by the main user flow.',completion_criteria='Core data can be created, read, updated, and validated through the intended backend interface.',required_skills=skills,resources=['Official backend and database documentation.']),
        ArchitectTask(title='Implement the primary user interface',description='Build the smallest interface that lets a user complete the main flow against real backend data.',completion_criteria='A user can complete the core flow without manually editing the database.',required_skills=stack[:2],resources=['Official frontend framework documentation.'])]),
      ArchitectMilestone(title='Validate & Present',objective='Make the project demonstrable and produce inspectable evidence.',tasks=[
        ArchitectTask(title='Add tests and failure states',description='Test important behavior and handle common invalid/error cases.',completion_criteria='Core happy path plus at least three important failure cases are tested or documented with reproducible validation.',required_skills=['Testing']+skills[:1],resources=['Framework testing documentation.']),
        ArchitectTask(title='Prepare README and demo evidence',description='Document setup, architecture decisions, completed scope, and a reproducible demonstration.',completion_criteria='A new reviewer can run or understand the project and identify the student’s meaningful contributions.',required_skills=['Git','Technical writing'],resources=['GitHub README and pull request best practices.'])])]
    return ArchitectPlan(project_summary=p.description,suggested_stack=stack,completion_definition=['Core user flow works with persisted data','Important failure states are handled','Setup and architecture are documented','Meaningful work can be reviewed through Git/PR evidence'],milestones=milestones,generated_by='local-demo',notice='Local demo architect used. Review and edit this plan before accepting it; it is guidance, not professional certification or an internship claim.')
